name: Cron job

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

env:
  SLACK_PAYLOAD_OUTPUT: /tmp/slack-payload.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' 
    - run: pip install -r requirements.txt
    - run: |
        ./notify_slack.sh ${{ env.SLACK_PAYLOAD_OUTPUT }}
    - name: Slack Notification 
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload-file-path: ${{ env.SLACK_PAYLOAD_OUTPUT }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK