name: Cron job

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Python script
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        pip install -r requirements.txt
        python main.py
        - name: Slack Notification
    - name: Slack Notification 
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: 
        SLACK_COLOR: ${{ job.status }} 
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'CM4 is available! :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}